### ISSUE TITLE
Problem with unreliable return value of 'git branch --show-current'

### ISSUE THREAD

**Issue by dervomsee** [br-na-pm/BuildVersion#20] opened 2024-10-23 12:36 UTC
When building a project with MS Devops the buildagent checks out a commit and not a branch. This results in a detached HEAD.
In this case the exit code $LASTEXITCODE of 'git branch --show-current' is unreliable. In a branch and detached $LASTEXITCODE is 0.

I extended the if condition here to check for $LASTEXITCODE and for '$null -eq $Branch': #19 

Here a screenshot of some commands in a test repo:
![image](https://github.com/user-attachments/assets/69547b92-6c2d-4951-814a-fa8266b5fdc0)

**Comment by tmatijevich** [comment] 2024-10-25 16:01
Thanks for sharing
This makes sense and I'm happy to merge the pull request

One thing I want to figure out first is - what is the scenario where `$LASTEXITCODE` is non-zero?
I wrote the warning message "Local repository is in a headless state" for some reason, but I can't remember why `$LASTEXITCODE` was able to see some headless state

**Comment by tmatijevich** [comment] 2024-10-30 01:46
I can't reproduce a detached head scenario where `$LASTEXITCODE` is non-zero
maybe it was an older version of git
PR merged and will close this for now

**Closed by tmatijevich** 2024-10-30 01:46 UTC
Labels: bug
